version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing tools...
      - pip install cfn-lint taskcat
  build:
    commands:
      - echo "Running cfn-lint to validate template syntax..."
      - cfn-lint Task2/resource.yaml
      - echo "Running taskcat lint..."
      - cd Task2
      - echo "Copy taskcat.yml to .taskcat.yml"
      - cp taskcat.yml .taskcat.yml
      - echo "Files in Task2:"
      - ls -la
      - taskcat lint