name: Terraform CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: Task1

      - name: Terraform Init
        run: terraform init
        working-directory: Task1

      - name: Terraform Validate
        run: terraform validate
        working-directory: Task1

      - name: Terraform Plan
        run: terraform plan
        working-directory: Task1

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@v12.2485.0
        with:
          directory: Task1
