name: Terraform Apply and Destroy (Manual)

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Init
        run: terraform init
        working-directory: Task1

      - name: Terraform Apply (Debug)
        run: export TF_LOG=DEBUG
          terraform apply -auto-approve
        working-directory: Task1

      - name: Wait for Testing (optional)
        run: sleep 60

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: Task1
